import { useState, useEffect } from 'react';
import Head from 'next/head';
import Footer from '../../components/Footer/Footer';
import ModalSingIn from '../../components/ModalSingIn/ModalSingIn';
import CardGallery from '../../components/CardGallery/CardGallery';

import styles from '../../styles/Galleries.module.css';

const Galleries = () => {
  const urlbase = process.env.NEXT_PUBLIC_URL_BASE;
  const [data, setData] = useState([]);

  const handleGalleries = async () => {
    const response = await fetch(`${urlbase}/galleries`);
    const json = await response.json();

    setData(json);
  };

  useEffect(() => {
    handleGalleries();
  }, []);

  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn'/>
        <h5 className={`text-uppercase fw-bolder text-center py-5 ${styles.title}`}>Galerias</h5>
      </header>

      <main className='mb-5 container-fluid'>
        <section className='row gx-0'>
          {
            data?.map((info, index) => (
              <div key={index} className='col-12 col-md-4 col-lg-3'>
                <CardGallery {...info} gallery />
              </div>
            ))
          }
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Galleries;
