import Head from 'next/head';
import PropTypes from 'prop-types';
import Carousel from '../components/Carousel/Carousel';
import Footer from '../components/Footer/Footer';
import Tab from '../components/Tab/Tab';

import styles from '../styles/Home.module.css';
import InfoSection from '../components/InfoSection/InfoSection';
import ModalSingIn from '../components/ModalSingIn/ModalSingIn';
import InfoSubs from '../components/InfoSubs/InfoSubs';

const Home = ({ carouselData, queens, galleries }) => {
  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <ModalSingIn idModal='singIn'/>
        <Carousel data={carouselData} />
      </header>

      <main className='mb-5'>
        <InfoSubs className='my-5' />
        <Tab queens={queens} galleries={galleries} />
        <InfoSection className="my-5" />
      </main>

      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const urlbase = process.env.NEXT_PUBLIC_URL_BASE;

  const resCarousel = await fetch(`${urlbase}/carousel`);
  const carouselData = await resCarousel.json();

  const resQueen = await fetch(`${urlbase}/queen`);
  const queens = await resQueen.json();

  const resGalleries = await fetch(`${urlbase}/galleries`);
  const galleries = await resGalleries.json();

  return {
    props: { carouselData, queens, galleries },
  };
}

Home.propTypes = {
  carouselData: PropTypes.array.isRequired,
  queens: PropTypes.array.isRequired,
  galleries: PropTypes.array.isRequired,
};

export default Home;
