import Head from 'next/head';
import Carousel from '../components/Carousel/Carousel';
import Navbar from '../components/Navbar/Navbar';
import carouselInfo from '../components/Carousel/carouselData.example.json';
import Footer from '../components/Footer/Footer';
import Tab from '../components/Tab/Tab';

import styles from '../styles/Home.module.css';
import InfoSection from '../components/InfoSection/InfoSection';

const Home = () => {
  return (
    <div className={styles.bgHome}>
      <Head>
        <title>My Queens Club - Enjoy The Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
        <Carousel carouselInfo={carouselInfo} />
      </header>

      <main className='mb-5'>
        <InfoSection className="my-5" />
        <Tab />
      </main>

      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();

  return {
    props: { data },
  };
}

export default Home;
